### ISSUE TITLE
Improve ADSR

### ISSUE THREAD

**Issue by tehsquidge** [tehsquidge/JSFM#1]
The current ADSR implementation isn't particularly great. It doesn't behave as a typical ADSR would. It should work like such:
1. a max value of 1.0, min of 0.0.
2. **A** is the time taken to increase to max (1.0)
3. **D** is the time taken to decrease to sustain. When sustain is max this will have no effect.
4. **S** the sustain level.
5. **R** time taken to decrease to 0.0

**Amp Env** will need it's own volume control at the bottom to attenuate.
**Pitch Env** will need a octave control at the bottom.

**Comment by stephen-oh** [comment]
An interesting feature would be having attack, decay and release as exponential curves rather than linear. This could perhaps be something you could toggle between

**Comment by tehsquidge** [comment]
I've experimented with switching to Exponential ramping. One thing I've been keeping in mind is that the ramping type used might depend on whether the Operator is a carrier or a modulator. Like, an Exponential Slope might be best for Release when it's a carrier because it is actually heard and sound is Logarithmic. I'm unsure if Linear is better when modulating.

I'll experiment with it again. :)
